import React from 'react';
import { X, FileText, Scale, CheckCircle2, AlertTriangle, ShieldCheck } from 'lucide-react';
import { playTactileClick } from '@utils/soundEffects';

export default function TermsOfServiceModal({ isOpen, onClose }) {
  if (!isOpen) return null;

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="terms-modal-title"
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 10000,
        background: 'rgba(4, 6, 10, 0.85)',
        backdropFilter: 'blur(16px)',
        WebkitBackdropFilter: 'blur(16px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '20px',
        animation: 'fadeIn 0.25s ease',
      }}
      onClick={(e) => {
        if (e.target === e.currentTarget) {
          playTactileClick();
          onClose();
        }
      }}
    >
      <div
        style={{
          width: '100%',
          maxWidth: '820px',
          maxHeight: '85vh',
          background: '#090d14',
          border: '1px solid rgba(212, 175, 55, 0.3)',
          borderRadius: '20px',
          boxShadow: '0 25px 60px rgba(0,0,0,0.8), 0 0 40px rgba(212, 175, 55, 0.1)',
          display: 'flex',
          flexDirection: 'column',
          overflow: 'hidden',
          color: '#f8f6f0',
        }}
      >
        {/* Header */}
        <div
          style={{
            padding: '24px 28px',
            borderBottom: '1px solid rgba(255, 255, 255, 0.08)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            background: 'linear-gradient(180deg, rgba(212, 175, 55, 0.06) 0%, transparent 100%)',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
            <div
              style={{
                width: '40px',
                height: '40px',
                borderRadius: '10px',
                background: 'rgba(212, 175, 55, 0.15)',
                border: '1px solid rgba(212, 175, 55, 0.3)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: '#d4af37',
              }}
            >
              <Scale size={22} />
            </div>
            <div>
              <h2
                id="terms-modal-title"
                style={{
                  fontFamily: "'Cinzel', serif",
                  fontSize: '1.25rem',
                  fontWeight: 700,
                  color: '#d4af37',
                  margin: 0,
                  letterSpacing: '0.04em',
                }}
              >
                BRAHMA Terms of Service & Sovereign Covenant
              </h2>
              <span style={{ fontSize: '0.78rem', color: 'rgba(248, 246, 240, 0.5)' }}>
                Version 3.2 • Governing Sovereign AI Architecture
              </span>
            </div>
          </div>

          <button
            onClick={() => {
              playTactileClick();
              onClose();
            }}
            aria-label="Close Terms of Service"
            style={{
              background: 'rgba(255, 255, 255, 0.05)',
              border: '1px solid rgba(255, 255, 255, 0.1)',
              borderRadius: '8px',
              padding: '8px',
              color: 'rgba(255, 255, 255, 0.7)',
              cursor: 'pointer',
            }}
          >
            <X size={18} />
          </button>
        </div>

        {/* Content Body */}
        <div
          style={{
            padding: '28px',
            overflowY: 'auto',
            fontSize: '0.9rem',
            lineHeight: 1.68,
            color: 'rgba(248, 246, 240, 0.85)',
          }}
        >
          <h3 style={{ color: '#d4af37', fontFamily: "'Cinzel', serif", fontSize: '1rem', marginTop: '0', marginBottom: '8px' }}>
            1. Acceptance of Terms
          </h3>
          <p>
            By accessing or initializing the BRAHMA Artificial Intelligence Operating System, its 13 Supreme Councils, autonomous swarm agents, or custom studios, you agree to be bound by these Terms of Service and all ethical safety covenants defined herein.
          </p>

          <h3 style={{ color: '#d4af37', fontFamily: "'Cinzel', serif", fontSize: '1rem', marginTop: '20px', marginBottom: '8px' }}>
            2. Intellectual Property & Code Ownership
          </h3>
          <p>
            All source code, applications, digital assets, mathematical proofs, and datasets generated by you utilizing BRAHMA remain <strong>100% your exclusive intellectual property</strong>. BRAHMA Labs claims zero ownership or copyright over creations synthesized in the workspace.
          </p>

          <h3 style={{ color: '#d4af37', fontFamily: "'Cinzel', serif", fontSize: '1rem', marginTop: '20px', marginBottom: '8px' }}>
            3. Ethical AI & Acceptable Use Policy (Dharma Guard)
          </h3>
          <p>
            You agree not to deploy BRAHMA swarm intelligence or formal reasoning engines to:
          </p>
          <ul style={{ paddingLeft: '20px', marginBottom: '16px' }}>
            <li>Generate malware, unauthorized network intrusion tools, or cyber weapons</li>
            <li>Produce non-consensual exploitative content or synthetic deception with malicious intent</li>
            <li>Circumvent legal safeguards, international sanctions, or vital infrastructure safety protocols</li>
          </ul>

          <h3 style={{ color: '#d4af37', fontFamily: "'Cinzel', serif", fontSize: '1rem', marginTop: '20px', marginBottom: '8px' }}>
            4. Limitation of Liability & AI Outputs
          </h3>
          <p>
            BRAHMA orchestrates frontier generative models and formal theorem provers (Lean 4). While rigorous verification heuristics are applied, AI outputs should be reviewed and verified by qualified professionals before deployment in life-critical, medical, or financial execution environments.
          </p>

          <h3 style={{ color: '#d4af37', fontFamily: "'Cinzel', serif", fontSize: '1rem', marginTop: '20px', marginBottom: '8px' }}>
            5. Termination & Modifications
          </h3>
          <p>
            You may terminate this agreement at any time by ceasing utilization of BRAHMA services and wiping local storage. BRAHMA Labs reserves the right to modify these terms to reflect evolving regulatory standards and frontier model safeguards.
          </p>
        </div>

        {/* Footer */}
        <div
          style={{
            padding: '16px 28px',
            borderTop: '1px solid rgba(255, 255, 255, 0.08)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'flex-end',
            background: 'rgba(0, 0, 0, 0.3)',
          }}
        >
          <button
            onClick={() => {
              playTactileClick();
              onClose();
            }}
            style={{
              padding: '9px 24px',
              borderRadius: '8px',
              background: 'linear-gradient(135deg, #d4af37 0%, #b89728 100%)',
              border: 'none',
              color: '#06080c',
              fontSize: '0.86rem',
              fontWeight: 700,
              cursor: 'pointer',
            }}
          >
            Agree & Accept
          </button>
        </div>
      </div>
    </div>
  );
}
