/**
 * BRAHMA AI — Document & Presentation Exporter Engine
 * 
 * Supports:
 * 1. Microsoft Word (.docx) generation with structured headings, formatted text, and styling
 * 2. Microsoft PowerPoint (.pptx) 16:9 widescreen slide deck generation with styled layouts
 */

import pptxgen from 'pptxgenjs';
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  Table,
  TableRow,
  TableCell,
  WidthType
} from 'docx';

/**
 * Trigger browser file download from Blob
 */
function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Clean markdown formatting helpers
 */
function stripMarkdownDecorations(text) {
  return text
    .replace(/^#+\s*/, '')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\[([^\]]+)\]\([^\)]+\)/g, '$1')
    .trim();
}

/**
 * ─────────────────────────────────────────────────────────────────────────────
 * 1. EXPORT TO MICROSOFT WORD (.DOCX)
 * ─────────────────────────────────────────────────────────────────────────────
 */
export async function exportToWordDocx(markdownText, documentTitle = 'Brahma AI Document') {
  if (!markdownText) return;

  const lines = markdownText.split('\n');
  const docChildren = [];

  // Document Cover / Title Header
  docChildren.push(
    new Paragraph({
      text: documentTitle,
      heading: HeadingLevel.TITLE,
      spacing: { after: 200, before: 100 },
      alignment: AlignmentType.CENTER
    })
  );

  docChildren.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by Brahma AI • ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`,
          italics: true,
          color: '666666',
          size: 20
        })
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 }
    })
  );

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    const line = rawLine.trim();

    if (!line) {
      docChildren.push(new Paragraph({ spacing: { after: 120 } }));
      continue;
    }

    // Heading 1 (# ...)
    if (line.startsWith('# ')) {
      docChildren.push(
        new Paragraph({
          text: stripMarkdownDecorations(line),
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 280, after: 140 }
        })
      );
    }
    // Heading 2 (## ...)
    else if (line.startsWith('## ')) {
      docChildren.push(
        new Paragraph({
          text: stripMarkdownDecorations(line),
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 220, after: 100 }
        })
      );
    }
    // Heading 3 (### ...)
    else if (line.startsWith('### ')) {
      docChildren.push(
        new Paragraph({
          text: stripMarkdownDecorations(line),
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 180, after: 80 }
        })
      );
    }
    // Bullet Points (* or -)
    else if (/^[\*\-]\s+/.test(line)) {
      const bulletContent = line.replace(/^[\*\-]\s+/, '');
      docChildren.push(
        new Paragraph({
          children: parseFormattedRuns(bulletContent),
          bullet: { level: 0 },
          spacing: { after: 80 }
        })
      );
    }
    // Numbered List (1. ...)
    else if (/^\d+\.\s+/.test(line)) {
      const itemContent = line.replace(/^\d+\.\s+/, '');
      docChildren.push(
        new Paragraph({
          children: parseFormattedRuns(itemContent),
          bullet: { level: 0 },
          spacing: { after: 80 }
        })
      );
    }
    // Standard Paragraph
    else {
      docChildren.push(
        new Paragraph({
          children: parseFormattedRuns(line),
          spacing: { after: 140, line: 276 }
        })
      );
    }
  }

  // Create Docx Document
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: docChildren
      }
    ]
  });

  const blob = await Packer.toBlob(doc);
  const cleanFilename = documentTitle.replace(/[^a-zA-Z0-9_\-\s]/g, '').trim().replace(/\s+/g, '_') || 'Brahma_Report';
  downloadBlob(blob, `${cleanFilename}.docx`);
}

/**
 * Helper to split bold/regular text into docx TextRuns
 */
function parseFormattedRuns(text) {
  const runs = [];
  const parts = text.split(/(\*\*[^*]+\*\*)/g);

  for (const part of parts) {
    if (!part) continue;
    if (part.startsWith('**') && part.endsWith('**')) {
      runs.push(
        new TextRun({
          text: part.slice(2, -2),
          bold: true
        })
      );
    } else {
      runs.push(
        new TextRun({
          text: part
        })
      );
    }
  }

  return runs.length > 0 ? runs : [new TextRun({ text })];
}

/**
 * ─────────────────────────────────────────────────────────────────────────────
 * 2. EXPORT TO MICROSOFT POWERPOINT (.PPTX)
 * ─────────────────────────────────────────────────────────────────────────────
 */
export async function exportToPowerPoint(markdownText, presentationTitle = 'Brahma AI Presentation') {
  if (!markdownText) return;

  const pptx = new pptxgen();
  pptx.layout = 'LAYOUT_16x9';

  // Define Theme Colors (Matching Brahma Aesthetics)
  const COLOR_BG = '0B0F19';       // Deep Void
  const COLOR_GOLD = 'F59E0B';     // Gold Accent
  const COLOR_CYAN = '06B6D4';     // Cyan Accent
  const COLOR_WHITE = 'F8FAFC';    // Crisp White Text
  const COLOR_MUTED = '94A3B8';    // Slate Muted Text
  const COLOR_CARD = '1E293B';     // Slide Card Box

  // Parse Markdown into Slide Blocks
  const slidesData = parseMarkdownToSlides(markdownText, presentationTitle);

  // ── Slide 1: Master Title Slide ───────────────────────────────────────────
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: COLOR_BG };

  // Decorative Accent Bar
  titleSlide.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: 0,
    w: 0.25,
    h: '100%',
    fill: { color: COLOR_GOLD }
  });

  // Title Text
  titleSlide.addText(presentationTitle, {
    x: 1.0,
    y: 2.2,
    w: 11.0,
    h: 1.5,
    fontSize: 38,
    bold: true,
    color: COLOR_WHITE,
    fontFace: 'Arial'
  });

  // Subtitle / Metadata
  titleSlide.addText('Executive Briefing & Strategic Overview • Generated by Brahma AI', {
    x: 1.0,
    y: 3.8,
    w: 10.0,
    h: 0.6,
    fontSize: 18,
    color: COLOR_GOLD,
    fontFace: 'Arial'
  });

  titleSlide.addText(new Date().toLocaleDateString('en-US', { dateStyle: 'long' }), {
    x: 1.0,
    y: 5.5,
    w: 8.0,
    h: 0.4,
    fontSize: 14,
    color: COLOR_MUTED,
    fontFace: 'Arial'
  });

  // ── Content Slides ─────────────────────────────────────────────────────────
  slidesData.forEach((slideItem, idx) => {
    const slide = pptx.addSlide();
    slide.background = { color: COLOR_BG };

    // Top Accent Stripe
    slide.addShape(pptx.ShapeType.rect, {
      x: 0.8,
      y: 0.5,
      w: 1.2,
      h: 0.06,
      fill: { color: COLOR_GOLD }
    });

    // Slide Header Title
    slide.addText(slideItem.title || `Key Insight ${idx + 1}`, {
      x: 0.8,
      y: 0.7,
      w: 11.5,
      h: 0.8,
      fontSize: 26,
      bold: true,
      color: COLOR_WHITE,
      fontFace: 'Arial'
    });

    // Main Content Card Background
    slide.addShape(pptx.ShapeType.roundRect, {
      x: 0.8,
      y: 1.7,
      w: 11.7,
      h: 5.0,
      rectRadius: 0.15,
      fill: { color: COLOR_CARD },
      line: { color: '334155', width: 1 }
    });

    // Bullet Points / Content Items
    if (slideItem.points && slideItem.points.length > 0) {
      const textItems = slideItem.points.map((pt) => ({
        text: pt,
        options: {
          bullet: { code: '2022' },
          breakLine: true,
          fontSize: 16,
          color: COLOR_WHITE,
          fontFace: 'Arial',
          paraSpaceAfter: 12
        }
      }));

      slide.addText(textItems, {
        x: 1.2,
        y: 2.1,
        w: 10.9,
        h: 4.2,
        valign: 'top'
      });
    }

    // Slide Footer
    slide.addText(`Brahma AI • Slide ${idx + 2}`, {
      x: 0.8,
      y: 6.9,
      w: 11.7,
      h: 0.3,
      fontSize: 10,
      color: COLOR_MUTED,
      fontFace: 'Arial',
      align: 'right'
    });
  });

  const cleanFilename = presentationTitle.replace(/[^a-zA-Z0-9_\-\s]/g, '').trim().replace(/\s+/g, '_') || 'Brahma_Presentation';
  await pptx.writeFile({ fileName: `${cleanFilename}.pptx` });
}

/**
 * Parses markdown headings & bullets into structured slide arrays
 */
function parseMarkdownToSlides(text, fallbackTitle) {
  const lines = text.split('\n');
  const slides = [];
  let currentSlide = null;

  for (let line of lines) {
    line = line.trim();
    if (!line) continue;

    // Detect slide section boundary (# or ##)
    if (line.startsWith('# ') || line.startsWith('## ') || line.startsWith('### ')) {
      if (currentSlide && currentSlide.points.length > 0) {
        slides.push(currentSlide);
      }
      currentSlide = {
        title: stripMarkdownDecorations(line),
        points: []
      };
    }
    // Bullet point
    else if (/^[\*\-]\s+/.test(line)) {
      const bullet = stripMarkdownDecorations(line.replace(/^[\*\-]\s+/, ''));
      if (!currentSlide) {
        currentSlide = { title: fallbackTitle, points: [] };
      }
      currentSlide.points.push(bullet);
    }
    // Regular text (sentence)
    else if (line.length > 15) {
      if (!currentSlide) {
        currentSlide = { title: fallbackTitle, points: [] };
      }
      // If slide already has 5 points, start a continuation slide
      if (currentSlide.points.length >= 5) {
        slides.push(currentSlide);
        currentSlide = { title: `${currentSlide.title} (Cont.)`, points: [] };
      }
      currentSlide.points.push(stripMarkdownDecorations(line));
    }
  }

  if (currentSlide && currentSlide.points.length > 0) {
    slides.push(currentSlide);
  }

  // If no sections were found, create a fallback single slide
  if (slides.length === 0) {
    slides.push({
      title: fallbackTitle,
      points: [
        'Strategic insights generated by Brahma AI.',
        'Review details in your complete session report.'
      ]
    });
  }

  return slides;
}
